### PR TITLE
py3 trove and universal wheels

### PR DESCRIPTION
**Pull request by graingert**
will need to be released with `python3 setup.py sdist bdist_wheel upload`

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Thanks!
I believe we now have to use Twine for uploading new versions. Does it still apply in that case?

**Comment by graingert** [comment]
You can still use twine with, `python3 setup.py sdist bdist_wheel && twine upload dist/*`

**Comment by graingert** [comment]
Can you release a .patch version @jonathanslenders ?

**Comment by jonathanslenders** [comment]
Thanks! I'll upload a new version this week. There are a few small things I'm preparing to include in the next release.

**Comment by graingert** [comment]
Could I get a .patch version with just the metadata change and wheel?

**Comment by jonathanslenders** [comment]
I pushed 2.0.5. Hope that helps.

**Pull request merged**
