### PR TITLE
implement XDG Base Directory specification

### LINKED ISSUE #63: support XDG spec
please use [`appdirs`](https://pypi.python.org/pypi/appdirs/1.4.0) to not pollute my `$HOME` with a `.ptpython` directory.

with `dirs = AppDirs('ptpython', 'Jonathan Slenders')`, your stuff should go into `dirs.user_data_dir`, `dirs.user_config_dir`, and  `dirs.user_cache_dir`

### LINKED ISSUE #132: Please use XDG paths for config.py and history by default
[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has been around for several years already. Please use recommended folders for storing `config.py` and `history` files.

`config.py` should be stored in `$XDG_CONFIG_HOME/ptpython/config.py` with fallback to `$HOME/.config/ptpython/config.py` if `$XDG_COFIG_HOME` is not set. You may fall back to `$HOME/.ptpython/config.py` is it wasn't found at XDG path and this file is present.

`history` should be stored in `$XDG_DATA_HOME/ptpython/history` with fallback to `$HOME/.local/share/ptpython/config.py` if `$XDG_DATA_HOME` is not set. Again you may fall back to `$HOME/.ptpython/history` if it wasn't found at XDG path and this file is present.

Ideally application should warn user that he is using legacy configuration path or just migrate automatically existing `config.py` and `history` to new locations.

Grand plan behind all of this is to eliminate dotfiles clutter from user's home folder.

### PR DESCRIPTION
**Pull request by carlwgeorge**
I accidentally deleted the fork I had for #183, so I'm recreating it.

* Use the appdirs module.
* Print a warning if the legacy ~/.ptpython directory is detected.
* Resolves #63.
* Resolves #132.

### CODE REVIEW

**Comment by stellarhoof** [comment]
Bumpity bump. This is nice.

**Comment by jonathanslenders** [comment]
Hey,

Thanks for reminding me on this!
If someone can rebase this pull request on the latest master, I'm willing to merge it.

Further, I'm thinking about using .toml configuration files. The reason is that with .toml it'll become possible to write changes back to the configuration file from within ptpython.
.toml doesn't have the flexibility that ``.ptpython/config.py`` has, so we will have to combine both.

**Comment by woegjiub** [comment]
@carlwgeorge Are you willing to rebase this?
If not, are you happy if I fork your repo and rebase?

**Comment by carlwgeorge** [comment]
Rebased.

**Comment by rpdelaney** [comment]
@jonathanslenders Is there anything stopping this from being merged?

**Comment by ObserverOfTime** [comment]
I'd love to see this merged.

**Comment by jonathanslenders** [comment]
I'm going to merge this. Thanks for all your patience!
(My priorities have been elsewhere. prompt_toolkit itself for instance.)

Instead of showing a warning, would it not be possible to automatically move the data directory into the XDG directory? Or maybe ask [y/n]?

**Comment by jonathanslenders** [comment]
Cherry-picked the commit here: https://github.com/prompt-toolkit/ptpython/commit/90c1dad98465d2da013a9ea5e34a29b95af8c687

**Comment by rpdelaney** [comment]
Thank you for merging!

> Instead of showing a warning, would it not be possible to automatically move the data directory into the XDG directory?

It would be possible, but it may annoy users who aren't themselves committed to following the freedesktop spec.

> Or maybe ask [y/n]?

Recording this response (so we don't ask every time we are invoked) would presumably go to the config file in a new setting of some kind. Is that worth it?

Simply falling back to old behavior if the XDG path isn't found may be simpler.

**Pull request closed without merging**
